# Generated by Django 3.0.4 on 2020-07-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='interested',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='userID',
            new_name='user',
        ),
    ]
