# Generated by Django 3.0.4 on 2020-07-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200709_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorcourse',
            name='courseID',
        ),
        migrations.AddField(
            model_name='mentorcourse',
            name='courseName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
