# Generated by Django 3.0.4 on 2020-07-12 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_mentorcourse_courseyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestedstudent',
            name='Course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.MentorCourse'),
        ),
        migrations.AlterField(
            model_name='interestedstudent',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.UserInfo'),
        ),
        migrations.AlterField(
            model_name='mentorcourse',
            name='currentIntersted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mentorcourse',
            name='maxInterested',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mentorcourse',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.UserInfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.User'),
        ),
    ]
