# Generated by Django 3.0.4 on 2020-07-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20200713_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, default='images/default_profile_img.jpg', null=True, upload_to='images/'),
        ),
    ]
