# Generated by Django 3.0.4 on 2020-07-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20200714_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, default='/media/images/default_profile_img.jpg', null=True, upload_to='media/images/'),
        ),
    ]
