# Generated by Django 3.0.4 on 2020-07-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20200714_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
