# Generated by Django 3.0.4 on 2020-07-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20200714_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='img',
            field=models.ImageField(blank=True, default='media/images/default_profile_img.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, default='media/images/default_profile_img.jpg', null=True, upload_to=''),
        ),
    ]
