# Generated by Django 3.0.4 on 2020-07-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_auto_20200714_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, default='static/images/default_profile_img.jpg', null=True, upload_to=''),
        ),
    ]
