# Generated by Django 3.0.4 on 2020-07-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20200714_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='about',
            field=models.TextField(default='אין פרטים להצגה', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='about',
            field=models.TextField(default='אין פרטים להצגה', null=True),
        ),
    ]
