# Generated by Django 3.0.4 on 2020-07-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20200718_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(blank=True, default='../static/images/courses-cover/default.jpg', null=True, upload_to=''),
        ),
    ]
