# Generated by Django 3.0.4 on 2020-07-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_course_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='datePublished',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='about',
            field=models.TextField(default='אין נתונים להצגה', null=True),
        ),
    ]
