# Generated by Django 3.0.4 on 2020-07-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20200720_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='about',
            field=models.TextField(default='אין נתונים להצגה', null=True),
        ),
    ]
